"""Team brain — read-only view over the team's git repository of markdown.

The team's brain LIVES in their git repository. It is not generated by
teammate; it is *authored* by the team (CLAUDE.md, runbooks, decision
records, onboarding docs) and committed to a private repo the team owns.

teammate provides:

  1. A read-only abstraction over the brain (this module).
  2. Indexing for local-LLM RAG (`teammate.rag`).
  3. MCP server exposure to Claude Code (`teammate.mcp_server`).
  4. Setup tooling that scaffolds a fresh brain repo from the bundled
     template (`teammate.init`).

The canonical layout (see `templates/team-brain-skeleton/` for the bundled
seed):

    <team-brain repo root>/
      CLAUDE.md                     - global team rules (loaded by Claude Code)
      .claude/
        skills/<name>/SKILL.md      - team-specific skills
        rules/{lint,commit,test}.md - split rules files
      docs/
        architecture/               - decision records, system diagrams
        runbooks/                   - on-call playbooks
        onboarding/                 - new-hire walkthroughs
      knowledge/
        people.md                   - who owns what
        services.md                 - what runs where
        decisions/                  - ADRs (architecture decision records)

Everything is plain markdown. Obsidian opens it without a plugin. `git
log` is the audit trail. Each developer has a local clone; the brain is
shared by virtue of being a normal git repository.
"""

from __future__ import annotations

from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml


@dataclass(frozen=True, slots=True)
class BrainEntry:
    """One markdown file inside the team brain."""

    path: Path
    relpath: str
    section: str  # claude | skills | rules | docs | knowledge | other
    title: str
    frontmatter: dict[str, Any]
    body: str


# ---------- helpers ----------


def _parse_frontmatter(raw: str) -> tuple[dict[str, Any], str]:
    if not raw.startswith("---"):
        return {}, raw
    closing = raw.find("\n---", 3)
    if closing == -1:
        return {}, raw
    fm_text = raw[3:closing].strip()
    body_start = raw.find("\n", closing + 4)
    body = raw[body_start + 1:] if body_start != -1 else ""
    try:
        fm = yaml.safe_load(fm_text) or {}
    except yaml.YAMLError:
        fm = {}
    return fm if isinstance(fm, dict) else {}, body


def _classify(relpath: str) -> str:
    if relpath in ("CLAUDE.md", ".claude/CLAUDE.md"):
        return "claude"
    if relpath.startswith(".claude/skills/"):
        return "skills"
    if relpath.startswith(".claude/rules/"):
        return "rules"
    if relpath.startswith("docs/"):
        return "docs"
    if relpath.startswith("knowledge/"):
        return "knowledge"
    return "other"


def _title_for(relpath: str, frontmatter: dict[str, Any], body: str) -> str:
    if "title" in frontmatter and isinstance(frontmatter["title"], str):
        return frontmatter["title"]
    for line in body.splitlines():
        line = line.strip()
        if line.startswith("# "):
            return line[2:].strip()
    return Path(relpath).stem


# ---------- public API ----------


class Brain:
    """Read-only view over a team-brain git repository."""

    def __init__(self, root: Path):
        self.root = Path(root).resolve()

    def exists(self) -> bool:
        return self.root.exists() and (self.root / "CLAUDE.md").exists()

    def iter_markdown(self) -> Iterator[BrainEntry]:
        """Yield every markdown file in the brain (skipping vendor/cache dirs)."""
        skip = {".git", "node_modules", ".teammate-cache", ".venv", "venv", "__pycache__"}
        for path in self.root.rglob("*.md"):
            if any(part in skip for part in path.parts):
                continue
            try:
                raw = path.read_text(encoding="utf-8")
            except OSError:
                continue
            fm, body = _parse_frontmatter(raw)
            relpath = str(path.relative_to(self.root))
            yield BrainEntry(
                path=path,
                relpath=relpath,
                section=_classify(relpath),
                title=_title_for(relpath, fm, body),
                frontmatter=fm,
                body=body,
            )

    def section(self, name: str) -> list[BrainEntry]:
        return [e for e in self.iter_markdown() if e.section == name]

    def claude_md(self) -> str | None:
        path = self.root / "CLAUDE.md"
        return path.read_text(encoding="utf-8") if path.exists() else None

    def stats(self) -> dict[str, int]:
        counts: dict[str, int] = {
            "total": 0,
            "claude": 0,
            "skills": 0,
            "rules": 0,
            "docs": 0,
            "knowledge": 0,
            "other": 0,
        }
        for entry in self.iter_markdown():
            counts["total"] += 1
            counts[entry.section] = counts.get(entry.section, 0) + 1
        return counts


__all__ = ["Brain", "BrainEntry"]
