"""Postmortem auto-drafter.

When an incident transitions to RESOLVED, this module:
1. Reads the timeline from `incident_events`
2. Reads the action checklist from `incident_preload`
3. Pulls similar past postmortems via Qdrant for tone-matching
4. Asks Ollama to draft a postmortem in markdown
5. Writes the draft to Confluence as a DRAFT page under the team's postmortem parent
6. NEVER auto-publishes — engineer must explicitly mark `status: published`

Output schema:
- Title:        "POSTMORTEM (DRAFT) — <incident.title> — <date>"
- Sections:     summary / timeline / root_cause / contributing / lessons / action_items
- Footer:       "Generated by vigil. Engineer review + edit + publish required."
"""

from __future__ import annotations

import logging
import os

log = logging.getLogger(__name__)


def draft_postmortem(incident_id: str) -> dict:
    """Generate the postmortem draft. Returns {confluence_page_id, status}."""
    timeline = _fetch_timeline(incident_id)
    preload = _fetch_preload(incident_id)

    markdown = _compose_markdown(incident_id, timeline, preload)
    page_id = _push_to_confluence(incident_id, markdown)

    return {"status": "drafted", "confluence_page_id": page_id}


def _compose_markdown(incident_id: str, timeline: list[dict], preload: dict) -> str:
    """Build the markdown postmortem from incident state."""
    title = preload.get("summary", f"Incident {incident_id}")
    lines = [
        f"# POSTMORTEM (DRAFT) — {title}",
        "",
        "> _Generated by vigil. Engineer review + edit + publish required._",
        "",
        "## Summary",
        preload.get("summary", "_to be edited_"),
        "",
        "## Timeline",
    ]
    for ev in timeline:
        ts = ev.get("created_at", "")
        actor = ev.get("actor", "")
        text = ev.get("payload", {}).get("text", ev.get("event_type", ""))
        lines.append(f"- **{ts}** · {actor} · {text}")

    lines.extend([
        "",
        "## Candidate root causes (LLM-drafted — DRAFT, please review)",
    ])
    for c in preload.get("candidate_causes", []):
        confidence = c.get("confidence", 0.0)
        lines.append(f"- _{confidence:.0%}_ — {c.get('cause', '')}")
        if c.get("supporting_evidence"):
            lines.append(f"  - evidence: {c['supporting_evidence']}")

    lines.extend([
        "",
        "## Action items (carried from war-room checklist)",
    ])
    for a in preload.get("actions", []):
        check = "x" if a.get("done") else " "
        lines.append(f"- [{check}] {a.get('text', '')}")

    lines.extend([
        "",
        "## Lessons (please fill in)",
        "- _to be edited_",
        "",
        "## Related",
    ])
    for s in preload.get("similar_incidents", []):
        lines.append(f"- {s.get('key', '')}: {s.get('title', '')} (similarity {s.get('score', 0):.2f})")

    return "\n".join(lines)


def _fetch_timeline(incident_id: str) -> list[dict]:
    try:
        import psycopg
    except ImportError:
        return []
    dsn = os.environ.get("POSTGRES_DSN", "")
    if not dsn:
        return []
    with psycopg.connect(dsn) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """SELECT event_type, actor, payload, created_at
                   FROM incident_events
                   WHERE incident_id = %s ORDER BY created_at ASC""",
                (incident_id,),
            )
            rows = cur.fetchall()
    return [
        {"event_type": r[0], "actor": r[1], "payload": r[2], "created_at": r[3].isoformat()}
        for r in rows
    ]


def _fetch_preload(incident_id: str) -> dict:
    try:
        import psycopg
    except ImportError:
        return {}
    dsn = os.environ.get("POSTGRES_DSN", "")
    if not dsn:
        return {}
    with psycopg.connect(dsn) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """SELECT summary, similar_incidents, candidate_causes,
                          runbooks, actions, participants
                   FROM incident_preload WHERE incident_id = %s""",
                (incident_id,),
            )
            row = cur.fetchone()
    if not row:
        return {}
    return {
        "summary": row[0],
        "similar_incidents": row[1] or [],
        "candidate_causes": row[2] or [],
        "runbooks": row[3] or [],
        "actions": row[4] or [],
        "participants": row[5] or [],
    }


def _push_to_confluence(incident_id: str, markdown: str) -> str | None:
    """Create a DRAFT Confluence page under the postmortem parent."""
    import httpx

    base = os.environ.get("CONFLUENCE_BASE_URL", "")
    email = os.environ.get("ATLASSIAN_EMAIL", "")
    token = os.environ.get("ATLASSIAN_API_TOKEN", "")
    space_id = os.environ.get("POSTMORTEM_SPACE_ID", "")
    parent_id = os.environ.get("POSTMORTEM_PARENT_ID", "")

    if not all([base, email, token, space_id, parent_id]):
        log.warning("postmortem confluence config incomplete; draft logged only for %s", incident_id)
        return None

    # Markdown → Confluence storage format. Use the same converter as daily_digest.
    from vigil.agent.daily_digest import _markdown_to_confluence_storage
    storage = _markdown_to_confluence_storage(markdown)

    with httpx.Client(auth=(email, token), timeout=30) as client:
        r = client.post(
            f"{base}/api/v2/pages",
            json={
                "spaceId": space_id,
                "status": "draft",
                "title": f"POSTMORTEM DRAFT — {incident_id}",
                "parentId": parent_id,
                "body": {"representation": "storage", "value": storage},
            },
        )
        if r.status_code not in (200, 201):
            log.warning("confluence draft failed: HTTP %d %s", r.status_code, r.text[:200])
            return None
        return r.json().get("id")
